### ISSUE TITLE
Repository move announcement

### ISSUE THREAD

**Issue by skirby1996** [iTwin/imodel-unity-example#23]
On Monday, October 4th, the imodel-unity-example repo will be transferred to the [iTwin Platform](https://github.com/iTwin) organization on Github.

All branches, pull requests, issues, and discussions will be transferred along with the repository, and all links to the old repository will redirect to the new repository which will be found at https://github.com/iTwin/imodel-unity-example.

Once the move is complete, we recommend that you update the git origin in your local copy of the repo to the new repository location using:

`git remote set-url origin https://github.com/iTwin/imodel-unity-example.git`

**Comment by skirby1996** [comment]
The imodel-unity-example repo has been successfully transferred to the iTwin Platform organization. Please use this thread if you experience any issues related to the transfer.

**Comment by mgooding** [comment]
Closing since no issues have been reported in the previous 6 months.
